TRAIN_FILES_DIR: '../data/joint_adv/RGB/noisy/train'
VAL_FILES_DIR: '../data/joint_adv/RGB/clean/val'
TEST_FILES_DIR: '../data/joint_adv/RGB/clean/test'
VIS_DIR: 'degrad_visualization'
BATCH_SIZE: 1
GPU_NUM: 1
USE_INSTANCE_NORM: False
USE_BILINEAR_RESIZE: False
USE_BINARIZE: False
USE_AVG_REPLICATE: True
NCHANNEL: 3
DEPTH: 16
WIDTH: 160
HEIGHT: 120
CROP_HEIGHT: 112
CROP_WIDTH: 112
USE_CROP: True
USE_RANDOM_CROP: False
USE_CENTER_CROP: True
NUM_THREADS: 10
NUM_EXAMPLES_PER_EPOCH: 500